apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prp-cm
  namespace: htcondor-portal
  labels:
    k8s-app: prp-cm
spec:
  replicas: 1
  serviceName: "prp-cm"
  selector:
    matchLabels:
      k8s-app: prp-cm
  template:
    metadata: 
      labels:
        k8s-app: prp-cm
    spec:
      nodeSelector:
        nautilus.io/latency: ucsd-b
      containers:
      - name: htcondor
        image: htcondor/cm:9.0-el7
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        resources:
           limits:
             memory: 4Gi
             cpu: 1
           requests:
             memory: 0.5Gi
             cpu: 0.1
        ports:
        - containerPort: 9618
        volumeMounts:
        - name: condordata
          mountPath: /var/lib/condor
        - name: condorlogs
          mountPath: /var/log/condor
        - name: configpasswd
          mountPath: /etc/condor/passwords.d/POOL
          subPath: POOL
          readOnly: true
      volumes:
      - name: condordata
        persistentVolumeClaim:
          claimName: prp-cm-pvc-state
      - name: condorlogs
        persistentVolumeClaim:
          claimName: prp-cm-pvc-logs
      - name: configpasswd
        secret:
          secretName: prp-cm-secret
          items:
             - key: POOL
               path: POOL
          defaultMode: 256

