apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: prp-cm-htcondor
  name: prp-cm-htcondor
  namespace: htcondor-portal
spec:
  ports:
  - port: 9618
    protocol: TCP
    targetPort: 9618
  selector:
    k8s-app: prp-cm
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
