apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prp-cm-pvc-state
  namespace: htcondor-portal
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prp-cm-pvc-logs
  namespace: htcondor-portal
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
