apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prp-schedd
  namespace: htcondor-portal
  labels:
    k8s-app: prp-schedd
spec:
  replicas: 1
  serviceName: "prp-schedd"
  selector:
    matchLabels:
      k8s-app: prp-schedd
  template:
    metadata: 
      labels:
        k8s-app: prp-schedd
    spec:
      nodeSelector:
        nautilus.io/latency: ucsd-b
      containers:
      - name: htcondor
        image: htcondor/submit:9.0-el7
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        env:
        - name: CONDOR_HOST
          value: "prp-cm-htcondor.htcondor-portal.svc.cluster.local"
        resources:
           limits:
             memory: 16Gi
             cpu: 4
           requests:
             memory: 2Gi
             cpu: 0.1
        ports:
        - containerPort: 9618
        volumeMounts:
        - name: condordata
          mountPath: /var/lib/condor
        - name: condorlogs
          mountPath: /var/log/condor
        - name: configpasswd
          mountPath: /etc/condor/tokens-orig.d/prp-schedd.token
          subPath: prp-schedd.token
          readOnly: true
        - name: config1sec
          mountPath: /etc/condor/config.d/01-security.conf
          subPath: 01-security.conf
        - name: config10sec
          mountPath: /etc/condor/config.d/10-security-multiuser-client.conf
          subPath: 10-security-multiuser-client.conf
      volumes:
      - name: condordata
        persistentVolumeClaim:
          claimName: prp-schedd-pvc-state
      - name: condorlogs
        persistentVolumeClaim:
          claimName: prp-schedd-pvc-logs
      - name: configpasswd
        secret:
          secretName: prp-schedd-secret
          items:
             - key: prp-schedd.token
               path: prp-schedd.token
          defaultMode: 256
      - name: config1sec
        configMap:
          name: prp-schedd-config
          items:
             - key: 01-security.conf
               path: 01-security.conf
      - name: config10sec
        configMap:
          name: prp-schedd-config
          items:
             - key: 10-security-multiuser-client.conf
               path: 10-security-multiuser-client.conf

