apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: prp-schedd-public
  name: prp-schedd-public
  namespace: htcondor-portal
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    k8s-app: prp-schedd
  type: LoadBalancer
